### ISSUE TITLE
Identify Best Items for Beginners to Use in Bokoblin Camps

### ISSUE THREAD

**Issue by Robert-Szlufik-L00188394** [Robert-Szlufik-L00188394/Project-and-Issues#3]
## Tasks:
- [ ] Compile a list of beginner-friendly items (weapons, potions, etc.).
- [ ] Consider both offensive and defensive items.
- [ ] Rank the items based on usefulness in beginner-level combat.
